### ISSUE TITLE
ToDo #001 - Create API Layer

### ISSUE THREAD

**Issue by jeremix** [jeremix/Bananas#1]
**#001 - Create API layer**
Required functions:
- [ ] 1.CalculateDistanceCoordinates [move from calendar.php]
  input : lat1,lng1,lat2,lng2;
  output: distance (km)
- [ ] 2.CalculateDistanceUsersDate
  input : userId1,userId2,Date[yyyy-mm-dd]
  output: distance (km)
- [ ] 3.Retrieve friends locations for Date/Date interval [move from calendar.php and complete].
  input: dateStart,dateEnd(optional)
  output: Json (Map<Date,ListOfFriendInfo**>)
  **_ListOfFriendInfo: Id,FirstName, LastName, (location)Name, Date, lat, lng_
- [ ] 4.Build Calendar [move from calendar.php and modify type of output. Does not requires any Query to DB]
  input: requiredMonthDifference (-1 return previous month, 0 current, 1 next, 2 two month ahead, etc..)
  output:Json (Map<Date, ListOfCellAttributes**>)
  ***ListOfCellAttributes: isDayOfCurrentMonth (true,false), DayNumber, isToday (true,false) *
- [ ] 5. User functions (login, logout, change password, get/edit personal info)
- [ ]  LIST TO BE COMPLETED - Check other ToDo's to find functions that may be useful (p.e.  #005 - insert event, retrieve events for user, modify event, etc.. )
