### ISSUE TITLE
ToDo #010 - Create user Settings Page

### ISSUE THREAD

**Issue by jeremix** [jeremix/Bananas#10]
**#010 - Create user Settings Page**
Tasks:
- [ ] 1.Add Settings button to main page
  Setting page functions:
- [ ] 2. Edit personal info
- [ ] 3. Change password
- [ ] 4. upload profile pic
- [ ] 5. change distance range for calendar colors ?? (requires DB update)
