### ISSUE TITLE
ToDo #004 - Day Detail Page

### ISSUE THREAD

**Issue by jeremix** [jeremix/Bananas#4]
**#004 - Day Detail Page**
Finalize Page:
- [ ] 1. On Marker Click show Friend Info (FirstName, LastName, Name(Location), DistancetoDateUserPosition
- [ ] 2. Add to Right Panel information about Day Events (if any, and if visible to user)
- [ ] 3. Add Option to Create/Edit Event
