### ISSUE TITLE
 ToDo #005 - Create new/edit Event page

### ISSUE THREAD

**Issue by jeremix** [jeremix/Bananas#5]
**#005 - Create new/edit Event page**
Required functions:
- [ ] 1. Add Event Location
- [ ] 2. Invite people
- [ ] 3. Add Event Date/Time
- [ ] 4. Set Event Visibility (Private - visible only to Invited, Public - visible to all friends)
- [ ] 5. Add Event Description
- [ ] 6. Set Event roles (Master - read/edit access; Attendee - read only access)
