### ISSUE TITLE
 ToDo #007 - Create Message Functionality

### ISSUE THREAD

**Issue by jeremix** [jeremix/Bananas#7]
**#007 - Create Message Functionality**
Required functions:
- [ ] 1. Create New Message button
- [ ] 2. Create "create new message" page
- [ ] 3. Add multiple people to message
- [ ] 4. Write and Send Message
- [ ] 5. Only display orange envelope when new message
- [ ] 6. View 2-3 most recent message preview in envelope dropdown
- [ ] 7. open message
- [ ] 8. Reply (creates new message - DB not ready for thread functionality)
