### ISSUE TITLE
ToDo #008 - Finalize Calendar

### ISSUE THREAD

**Issue by jeremix** [jeremix/Bananas#8]
**#008 - Finalize Calendar**
Required functions:
- [ ] 1.Display color according to Closest Friend (red - distance>xxx, orange - xx>distance>xxx - green x>distance)
- [ ] 2. On click "colored" Day show small popup with top5 closest friends on that day (Name - locationName - distance km) , and button to DayDetail.
- [ ] 3. If not colored, on click open DayDetail
- [ ] 4. Add Filter functionality (only displays calendar color for selected Friend), check http://stackoverflow.com/questions/23034772/integrating-image-with-jquery-autocomplete for auto-complete search box
